### ISSUE TITLE
OGRe.m crashes while opening

### ISSUE THREAD

**Issue by sugr-wq** [bshoshany/OGRe#10]
I found the OGRe package just today. I downloaded the file OGRe.m on my computer. Every time I try to open it, I see the the kind of screen shown in the attached picture, after which OGRe.m crashes and closes. 
![Opening OGRe](https://github.com/user-attachments/assets/e62c004d-6874-4c74-98e0-785531fdade7)

So I'm unable to open OGRe.m

**Comment by bshoshany** [comment]
Hi @sugr-wq and thanks for opening this issue!

To use the package, you actually don't need to open `OGRe.m` itself for editing. Please see instruction on the main page of the GitHub repository under ["Installing and loading the package"](https://github.com/bshoshany/OGRe#installing-and-loading-the-package).

The easiest way is to run the command `URLDownload["https://raw.githubusercontent.com/bshoshany/OGRe/master/OGRe.m", FileNameJoin[{$UserBaseDirectory, "Applications", "OGRe.m"}]]` in any Mathematica notebook, which will install the package so that it can then be loaded into any notebook using the command ``Needs["OGRe`"]``.

Now, there are some reason to open `OGRe.m` itself, for example to modify the package's source code in order to add new features. However, I don't think that is what you want to do if you just discovered the package today. In any case, I tried it on my computer right now (Mathematica 14.1) and the file opened without problem. If you do wish to modify the package's source code, then we can try to figure out together why it crashes on your computer (perhaps due to a corrupted Mathematica installation), but like I said, if you just want to use the package for doing tensor calculations, please follow the instructions linked above.

Hope this helps!

**Comment by bshoshany** [comment]
I am happy to announce that [OGRe v2.0.0](https://github.com/bshoshany/OGRe/releases/tag/v2.0.0) is now released! Please make sure to update to the latest version; this can be done automatically with `TCheckForUpdates[]`. I would greatly appreciate it if you could pass the news to any colleagues who are using OGRe or might be interested in using it. Please let me know if you have any additional feedback.
