### ISSUE TITLE
Supporting symbol keys or auto-completion of string keys

### ISSUE THREAD

**Issue by yuriever** [bshoshany/OGRe#4]
Hi! I'm new using your package and have only read part of the code. I just wonder is it okay to support `Symbol` keys like replacing

```
TNewCoordinates[coordinatesID_String, coordinates_List?VectorQ] := 
```

by

```
keytype=(_String|_Symbol)
TNewCoordinates[coordinatesID:keytype, coordinates_List?VectorQ] := 
```
Will this replacement of patterns break codes in other place?

Or if supporting `Symbol` keys is hard, can `String` keys be auto-completed by 

```
FE`Evaluate@FEPrivate`AddSpecialArgCompletion[_];
```

in [this answer](https://mathematica.stackexchange.com/a/129910/86893). Where are the right places to add this function?

**Comment by bshoshany** [comment]
Hi @yuriever, thanks for opening this issue. Sorry it took me so long to reply. I'm currently on hiatus from developing this package, since I'm too busy teaching. However, I plan to release a new version with many bug fixes and new features in the summer.

I have considered replacing the strings with symbol names, but I'm not sure this is a good idea, since it will make it easier to break encapsulation. However, I do plan on adding autocomplete for the object names. It won't be in the way that you suggest, since that is an undocumented and possibly broken feature, but I might use [`AddCodeCompletion`](https://resources.wolframcloud.com/FunctionRepository/resources/AddCodeCompletion) or something similar.

Closing this issue since this is already planned to be implemented in the next release.

**Comment by bshoshany** [comment]
I am happy to announce that [OGRe v2.0.0](https://github.com/bshoshany/OGRe/releases/tag/v2.0.0) is now released, and supports auto-completion of tensor IDs! Please make sure to update to the latest version; this can be done automatically with `TCheckForUpdates[]`. I would greatly appreciate it if you could pass the news to any colleagues who are using OGRe or might be interested in using it. Please let me know if you have any additional feedback.
