### ISSUE TITLE
[Feature request] Laplace/d'Alembert  operators

### ISSUE THREAD

**Issue by AlexLight2023** [bshoshany/OGRe#5]
The calculation of Laplace/d'Alembert operators for scalar/vector/tensor fields is very common in GR research. Can you add them to your package?

**Comment by bshoshany** [comment]
Hi @AlexLight2023, thanks for opening this issue. Sorry it took me so long to reply. I'm currently on hiatus from developing this package, since I'm too busy teaching. However, I plan to release a new version with many bug fixes and new features in the summer.

I will implement Laplace/d'Alembert operators in the next release, per your request! For now, I am closing this issue.
