### ISSUE TITLE
Convert Tensors to Functions

### ISSUE THREAD

**Issue by neogi-sayan** [bshoshany/OGRe#6]
I couldn't figure if there is a way to convert tensors to usual Mathematica functions so that we could use them in other packages like VariationalD.

**Comment by bshoshany** [comment]
Hi @Sayan2001, thanks for opening this issue. Sorry it took me so long to reply. I'm currently on hiatus from developing this package, since I'm too busy teaching. However, I plan to release a new version with many bug fixes and new features in the summer.

Sorry, I'm not exactly sure what you mean by "converting tensors to functions". The module `TGetComponents[]` returns the components of the tensor as a Mathematica `List`. Is that what you are looking for?

**Comment by bshoshany** [comment]
I am happy to announce that [OGRe v2.0.0](https://github.com/bshoshany/OGRe/releases/tag/v2.0.0) is now released! Please make sure to update to the latest version; this can be done automatically with `TCheckForUpdates[]`. I would greatly appreciate it if you could pass the news to any colleagues who are using OGRe or might be interested in using it. Please let me know if you have any additional feedback.
