### ISSUE TITLE
[Feature-Request] Abstract tensors and computing a single component of a tensor

### ISSUE THREAD

**Issue by alves-nickolas** [bshoshany/OGRe#9]
Dear Barak,
In some calculations I perform, I need to deal with an "abstract tensor", in the sense I do not know the specific components of it. Currently, I typeset this manually by entering, say, `Tij[t,x,y,z]` in the components. This, however, leads to horrible expressions when I convert tensors defined upon `T` to, say, spherical coordinates, since `Tij` are the Cartesian components of `T`. The expressions would be simpler if the package automatically wrote the spherical components instead of the Cartesian components.

A second suggestion involves computing large tensors. Consider a somewhat general metric, such as a generic GW spacetime in TT gauge. In my experience, computing the Riemann tensor for this metric with OGRe is a bit lengthy for an arbitrary GW whose specific components I do not know. Nevertheless, in some calculations, I just want one of the components of the Riemann tensor, so there is no need to compute all 256 entries. It would be nice to have a way to tell the code to compute only one specific entry. 

Thank you very much for your attention and your great package!

**Comment by bshoshany** [comment]
Hi @alves-nickolas and thanks so much for these suggestions. It has been almost 3 years since I last updated OGRe, because I've been mostly focused on other projects - including a Python port of OGRe, which is very close to being released! Once I'm done with the Python port, I will have more time to work on a new and improved release of OGRe, and I will certainly take your suggestions under consideration. Both of them seem easy enough to implement, but I also currently have about 150 (!) other items on my TODO list, so it might take some time before I get to them. If you have any other feature requests, please feel free to write them here.
